name: MDUpdater
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  md-updater:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: pip install
      run: if [ -f '.github/workflows/requirements.txt' ];then pip install -r .github/workflows/requirements.txt;fi
    - name: Update
      run: python .github/workflows/json_md.py
    - name: GH commit
      uses: stefanzweifel/git-auto-commit-action@v7
      with:
        file_pattern: "*.md"
        push_token: ${{ secrets.GITHUB_TOKEN }}