name: VersionUpdater
on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: '0 22 * * *'
  push:
    branches:
      - main
jobs:
  version-updater:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: pip install
      run: if [ -f '.github/workflows/requirements.txt' ];then pip install -r .github/workflows/requirements.txt;fi
    - name: Update
      run: python .github/workflows/json_to_markdown.py
    - name: GH commit
      uses: stefanzweifel/git-auto-commit-action@v7
      with:
        file_pattern: "*.md"